#!/bin/bash
#PBS -N vpr_yoto_df_prio_adder_k6_0
#PBS -l nodes=1:ppn=1,mem=10240mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o adder_k6_0.pbs.out
#PBS -e adder_k6_0.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yoto_df_prio/net/adder_k6_0.net" arch/k6-n1.xml "reports/fpga/EPFL/yoto_df_prio/place/adder_k6_0.place" "reports/fpga/EPFL/yoto_df_prio/rep/adder_k6_0.route" --route_only -nodisp > "reports/fpga/EPFL/yoto_df_prio/rep/adder_k6_0.out"
