#!/bin/bash

bin/vpr "benchmarks/fpga/net_EPFL/voter_k6.net" arch/k6-n1.xml "voter_k6.place" "voter_k6.route" -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "voter_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/sqrt_k6.net" arch/k6-n1.xml "sqrt_k6.place" "sqrt_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "sqrt_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/sin_k6.net" arch/k6-n1.xml "sin_k6.place" "sin_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "sin_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/router_k6.net" arch/k6-n1.xml "router_k6.place" "router_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "router_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/priority_k6.net" arch/k6-n1.xml "priority_k6.place" "priority_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "priority_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/multiplier_k6.net" arch/k6-n1.xml "multiplier_k6.place" "multiplier_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "multiplier_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/max_k6.net" arch/k6-n1.xml "max_k6.place" "max_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "max_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/log2_k6.net" arch/k6-n1.xml "log2_k6.place" "log2_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "log2_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/int2float_k6.net" arch/k6-n1.xml "int2float_k6.place" "int2float_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "int2float_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/i2c_k6.net" arch/k6-n1.xml "i2c_k6.place" "i2c_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "i2c_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/div_k6.net" arch/k6-n1.xml "div_k6.place" "div_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "div_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/dec_k6.net" arch/k6-n1.xml "dec_k6.place" "dec_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "dec_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/ctrl_k6.net" arch/k6-n1.xml "ctrl_k6.place" "ctrl_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "ctrl_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/cavlc_k6.net" arch/k6-n1.xml "cavlc_k6.place" "cavlc_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "cavlc_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/bar_k6.net" arch/k6-n1.xml "bar_k6.place" "bar_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "bar_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/adder_k6.net" arch/k6-n1.xml "adder_k6.place" "adder_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "adder_k6.out"
bin/vpr "benchmarks/fpga/net_EPFL/square_k6.net" arch/k6-n1.xml "square_k6.place" "square_k6.route"  -place_only -nodisp  -timing_analysis on -enable_timing_computations off  -place_algorithm bounding_box  > "square_k6.out"
