#!/bin/bash
#PBS -N vpr_sa_max_k6_7
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o max_k6_7.pbs.out
#PBS -e max_k6_7.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/sa/net/max_k6_7.net" arch/k6-n1.xml "reports/fpga/EPFL/sa/place/max_k6_7.place" "reports/fpga/EPFL/sa/rep/max_k6_7.route" --route_only -nodisp > "reports/fpga/EPFL/sa/rep/max_k6_7.out"
