#!/bin/bash
#PBS -N vpr_yoto_df_prio_cavlc_k6_8
#PBS -l nodes=1:ppn=1,mem=10240mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o cavlc_k6_8.pbs.out
#PBS -e cavlc_k6_8.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yoto_df_prio/net/cavlc_k6_8.net" arch/k6-n1.xml "reports/fpga/EPFL/yoto_df_prio/place/cavlc_k6_8.place" "reports/fpga/EPFL/yoto_df_prio/rep/cavlc_k6_8.route" --route_only -nodisp > "reports/fpga/EPFL/yoto_df_prio/rep/cavlc_k6_8.out"
