#!/bin/bash
#PBS -N vpr_yoto_df_prio_ctrl_k6_3
#PBS -l nodes=1:ppn=1,mem=10240mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o ctrl_k6_3.pbs.out
#PBS -e ctrl_k6_3.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yoto_df_prio/net/ctrl_k6_3.net" arch/k6-n1.xml "reports/fpga/EPFL/yoto_df_prio/place/ctrl_k6_3.place" "reports/fpga/EPFL/yoto_df_prio/rep/ctrl_k6_3.route" --route_only -nodisp > "reports/fpga/EPFL/yoto_df_prio/rep/ctrl_k6_3.out"
