#!/bin/bash
#PBS -N vpr_yoto_df_prio_dec_k6_4
#PBS -l nodes=1:ppn=1,mem=10240mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o dec_k6_4.pbs.out
#PBS -e dec_k6_4.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yoto_df_prio/net/dec_k6_4.net" arch/k6-n1.xml "reports/fpga/EPFL/yoto_df_prio/place/dec_k6_4.place" "reports/fpga/EPFL/yoto_df_prio/rep/dec_k6_4.route" --route_only -nodisp > "reports/fpga/EPFL/yoto_df_prio/rep/dec_k6_4.out"
