#!/bin/bash
#PBS -N vpr_yoto_df_prio_sin_k6_6
#PBS -l nodes=1:ppn=1,mem=10240mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o sin_k6_6.pbs.out
#PBS -e sin_k6_6.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yoto_df_prio/net/sin_k6_6.net" arch/k6-n1.xml "reports/fpga/EPFL/yoto_df_prio/place/sin_k6_6.place" "reports/fpga/EPFL/yoto_df_prio/rep/sin_k6_6.route" --route_only -nodisp > "reports/fpga/EPFL/yoto_df_prio/rep/sin_k6_6.out"
