#!/bin/bash
#PBS -N vpr_sa_div_k6_4
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o div_k6_4.pbs.out
#PBS -e div_k6_4.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/sa/net/div_k6_4.net" arch/k6-n1.xml "reports/fpga/EPFL/sa/place/div_k6_4.place" "reports/fpga/EPFL/sa/rep/div_k6_4.route" --route_only -nodisp > "reports/fpga/EPFL/sa/rep/div_k6_4.out"
