#!/bin/bash
#PBS -N vpr_sa_log2_k6_0
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o log2_k6_0.pbs.out
#PBS -e log2_k6_0.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/sa/net/log2_k6_0.net" arch/k6-n1.xml "reports/fpga/EPFL/sa/place/log2_k6_0.place" "reports/fpga/EPFL/sa/rep/log2_k6_0.route" --route_only -nodisp > "reports/fpga/EPFL/sa/rep/log2_k6_0.out"
