#!/bin/bash
#PBS -N vpr_sa_multiplier_k6_3
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o multiplier_k6_3.pbs.out
#PBS -e multiplier_k6_3.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/sa/net/multiplier_k6_3.net" arch/k6-n1.xml "reports/fpga/EPFL/sa/place/multiplier_k6_3.place" "reports/fpga/EPFL/sa/rep/multiplier_k6_3.route" --route_only -nodisp > "reports/fpga/EPFL/sa/rep/multiplier_k6_3.out"
