#!/bin/bash
#PBS -N vpr_sa_router_k6_9
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o router_k6_9.pbs.out
#PBS -e router_k6_9.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/sa/net/router_k6_9.net" arch/k6-n1.xml "reports/fpga/EPFL/sa/place/router_k6_9.place" "reports/fpga/EPFL/sa/rep/router_k6_9.route" --route_only -nodisp > "reports/fpga/EPFL/sa/rep/router_k6_9.out"
