#!/bin/bash
#PBS -N vpr_sa_sin_k6_9
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o sin_k6_9.pbs.out
#PBS -e sin_k6_9.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/sa/net/sin_k6_9.net" arch/k6-n1.xml "reports/fpga/EPFL/sa/place/sin_k6_9.place" "reports/fpga/EPFL/sa/rep/sin_k6_9.route" --route_only -nodisp > "reports/fpga/EPFL/sa/rep/sin_k6_9.out"
