#!/bin/bash
#PBS -N vpr_sa_voter_k6_6
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o voter_k6_6.pbs.out
#PBS -e voter_k6_6.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/sa/net/voter_k6_6.net" arch/k6-n1.xml "reports/fpga/EPFL/sa/place/voter_k6_6.place" "reports/fpga/EPFL/sa/rep/voter_k6_6.route" --route_only -nodisp > "reports/fpga/EPFL/sa/rep/voter_k6_6.out"
