#!/bin/bash
#PBS -N vpr_yoto_df_router_k6_0
#PBS -l nodes=1:ppn=1,mem=10240mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o router_k6_0.pbs.out
#PBS -e router_k6_0.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yoto_df/net/router_k6_0.net" arch/k6-n1.xml "reports/fpga/EPFL/yoto_df/place/router_k6_0.place" "reports/fpga/EPFL/yoto_df/rep/router_k6_0.route" --route_only -nodisp > "reports/fpga/EPFL/yoto_df/rep/router_k6_0.out"
