#!/bin/bash
#PBS -N vpr_yoto_df_square_k6_6
#PBS -l nodes=1:ppn=1,mem=10240mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o square_k6_6.pbs.out
#PBS -e square_k6_6.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yoto_df/net/square_k6_6.net" arch/k6-n1.xml "reports/fpga/EPFL/yoto_df/place/square_k6_6.place" "reports/fpga/EPFL/yoto_df/rep/square_k6_6.route" --route_only -nodisp > "reports/fpga/EPFL/yoto_df/rep/square_k6_6.out"
