#!/bin/bash
#PBS -N vpr_yott_cavlc_k6_1
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o cavlc_k6_1.pbs.out
#PBS -e cavlc_k6_1.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yott/net/cavlc_k6_1.net" arch/k6-n1.xml "reports/fpga/EPFL/yott/place/cavlc_k6_1.place" "reports/fpga/EPFL/yott/rep/cavlc_k6_1.route" --route_only -nodisp > "reports/fpga/EPFL/yott/rep/cavlc_k6_1.out"
