#!/bin/bash
#PBS -N vpr_yott_dec_k6_2
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o dec_k6_2.pbs.out
#PBS -e dec_k6_2.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yott/net/dec_k6_2.net" arch/k6-n1.xml "reports/fpga/EPFL/yott/place/dec_k6_2.place" "reports/fpga/EPFL/yott/rep/dec_k6_2.route" --route_only -nodisp > "reports/fpga/EPFL/yott/rep/dec_k6_2.out"
