#!/bin/bash
#PBS -N vpr_yott_i2c_k6_5
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o i2c_k6_5.pbs.out
#PBS -e i2c_k6_5.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yott/net/i2c_k6_5.net" arch/k6-n1.xml "reports/fpga/EPFL/yott/place/i2c_k6_5.place" "reports/fpga/EPFL/yott/rep/i2c_k6_5.route" --route_only -nodisp > "reports/fpga/EPFL/yott/rep/i2c_k6_5.out"
