#!/bin/bash
#PBS -N vpr_yott_ctrl_k6_6
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o ctrl_k6_6.pbs.out
#PBS -e ctrl_k6_6.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yott/net/ctrl_k6_6.net" arch/k6-n1.xml "reports/fpga/EPFL/yott/place/ctrl_k6_6.place" "reports/fpga/EPFL/yott/rep/ctrl_k6_6.route" --route_only -nodisp > "reports/fpga/EPFL/yott/rep/ctrl_k6_6.out"
