#!/bin/bash
#PBS -N vpr_yott_priority_k6_8
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o priority_k6_8.pbs.out
#PBS -e priority_k6_8.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yott/net/priority_k6_8.net" arch/k6-n1.xml "reports/fpga/EPFL/yott/place/priority_k6_8.place" "reports/fpga/EPFL/yott/rep/priority_k6_8.route" --route_only -nodisp > "reports/fpga/EPFL/yott/rep/priority_k6_8.out"
