#!/bin/bash
#PBS -N vpr_yott_voter_k6_7
#PBS -l nodes=1:ppn=1,mem=4192mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o voter_k6_7.pbs.out
#PBS -e voter_k6_7.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yott/net/voter_k6_7.net" arch/k6-n1.xml "reports/fpga/EPFL/yott/place/voter_k6_7.place" "reports/fpga/EPFL/yott/rep/voter_k6_7.route" --route_only -nodisp > "reports/fpga/EPFL/yott/rep/voter_k6_7.out"
