#!/bin/bash
#PBS -N vpr_yoto_df_log2_k6_9
#PBS -l nodes=1:ppn=1,mem=10240mb
#PBS -m ae
#PBS -M jeronimo.penha@ufv.br
#PBS -o log2_k6_9.pbs.out
#PBS -e log2_k6_9.pbs.err
#PBS -V

cd $PBS_O_WORKDIR

bin/vpr "reports/fpga/EPFL/yoto_df/net/log2_k6_9.net" arch/k6-n1.xml "reports/fpga/EPFL/yoto_df/place/log2_k6_9.place" "reports/fpga/EPFL/yoto_df/rep/log2_k6_9.route" --route_only -nodisp > "reports/fpga/EPFL/yoto_df/rep/log2_k6_9.out"
